POST http://localhost:7071/api/RegisterNewScore HTTP/1.1
content-type: application/json

{
    "username": "koooOOOooooOoOOOofoed  ",
    "email": "anders.kfd@gmail.com  ",
    "score": 400
}

###

GET http://localhost:7071/api/FetchHighScores HTTP/1.1