POST https://flappy-nerd.azurewebsites.net/api/RegisterNewScore?code=6WQ5BsRP08zWwCWQRId7bWJEvSRsBtX4V31w1JdofnacSy071b4G/A== HTTP/1.1

{
    "username": "koooOOOooooOoOOOofoed  ",
    "email": "anders.kfd@gmail.com  ",
    "score": 400
}

###

GET  https://flappy-nerd.azurewebsites.net/api/FetchHighScores?code=6WQ5BsRP08zWwCWQRId7bWJEvSRsBtX4V31w1JdofnacSy071b4G/A== HTTP/1.1